#!/bin/bash

# Usage ./demo.sh file_name

# Take the file as input
FILENAME=$1

# Declare an array and read the input file line by line
declare -a MY_ARRAY
while read -r LINE
do
    # Factorize the number and store the result in the array
    MY_ARRAY=("$LINE" $(factor "$LINE" | awk '{print $2}' ))
    RESULT=$((MY_ARRAY[0] / MY_ARRAY[1]))
    printf '%s=%s*%s\n' "${MY_ARRAY[0]}" "$RESULT" "${MY_ARRAY[1]}"
done < "$FILENAME"
